openapi: 3.0.1
info:
  title: APIs.io Engine API
  description: This is the engine of the API search engine.
  version: V1
  
servers:

  - url: https://8wmp1s1pni.execute-api.us-east-1.amazonaws.com/staging

paths:

  '/engine/apisjson/apis/properties':
    put:
      operationId: processesAPIProperties
      responses:
        200:
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:m-s-apis-io-engineapisproperties-pu/invocations
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
        type: aws

  '/engine/apisjson':
    put:
      operationId: processesAPIsJSON
      responses:
        200:
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:m-s-engine-apisjson-pu/invocations
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
        type: aws

components:
  schemas:
    Object:
      required:
      - description
      - run
      type: object
      properties:
        status:
          type: string
        description:
          type: string